Feat: now have 103 and 426 http-codes
prettymuchbryce/http-status-codes pull request #89
Opened 2022-10-01 14:31 UTC by angellee177

fix issue for this ticket [https://github.com/prettymuchbryce/http-status-codes/issues/20](url)

2022-10-01 14:32 UTC, angellee177 commented
@prettymuchbryce please kindly review this PR. :)

2022-10-12 09:39 UTC, angellee177 commented
@prettymuchbryce is there anything i need to changes or fix?

2022-10-17 14:59 UTC, angellee177 commented
@JameelKhan9 @sebdeckers @narqo @tlhunter is there anyone can review this PR?

2023-09-17 14:48 UTC, pacifiquem commented
@angellee177 map this issue (  #20 ) to this pull request so that it'll be closed as soon as this pull request is merged.
also everything looks good @prettymuchbryce it can be merged.

2023-09-17 14:51 UTC, pacifiquem approved these changes
@angellee177 map this issue ( https://github.com/prettymuchbryce/http-status-codes/issues/20 ) to this pull request so that it'll be closed as soon as this pull request is merged.
also everything looks good @prettymuchbryce it can be merged.

2023-09-17 14:51 UTC, angelsupp commented
thank you for reviewing my PR @pacifiquem :) can you help me to merge the PR?

2023-09-17 14:53 UTC, pacifiquem commented
No @angelsupp we've to wait for @prettymuchbryce or any other maintainer to merge it. Since everything looks good let's hope they'll merge it soon :).

2023-09-17 14:58 UTC, angelsupp commented
thanks a lot @pacifiquem 😆

2023-09-18 07:30 UTC, prettymuchbryce commented
Thank you and apologies for my delayed response. It looks like HTTP 521 is not an official status code, but instead is specific to CloudFlare. The documentation linked in this PR
[here](https://datatracker.ietf.org/doc/html/rfc7504#section-3) is for an unrelated SMTP (not HTTP) error.

I would prefer not to include codes without an official RFC. If we can remove HTTP 521 from this PR then I will happily merge the PR 103 and 426 look good to me!

2023-09-18 07:50 UTC, pacifiquem requested changes
@angellee177 @angelsupp  remove 521 status code as suggested by @prettymuchbryce and this PR will be merged. Also remember to map issue #20 so that it will be closed immediately as 103 status code will be added.

2023-09-18 07:50 UTC, pacifiquem commented on codes.json
> +  },
It looks like HTTP 521 is not an official status code, but instead is specific to CloudFlare. The documentation linked in this PR [here](https://datatracker.ietf.org/doc/html/rfc7504#section-3) is for an unrelated SMTP (not HTTP) error.

@angellee177 or @angelsupp remove this status code ( 521 ) and this PR will be merged as suggested by @prettymuchbryce

2023-09-18 07:54 UTC, pacifiquem commented
Closes #20

2023-09-18 11:19 UTC, angelsupp commented
let me remove the 521 status code @pacifiquem @prettymuchbryce

2023-09-18 12:10 UTC, angelsupp commented
done @prettymuchbryce @pacifiquem 😆
[here](https://github.com/prettymuchbryce/http-status-codes/pull/89/commits/7b84773c9da8e9f92fe364d8991362490a2e68c2) is the commit.

2023-09-18 12:35 UTC, pacifiquem approved these changes
LGTM :+1:

2023-09-18 12:36 UTC, pacifiquem commented
@prettymuchbryce let's merge it.

2023-09-20 09:54 UTC, merged

2023-09-20 12:36 UTC, pacifiquem commented
Thank you @angelsupp for your contribution.